mugloar:
    base-url: https://dragonsofmugloar.com
spring:
    application:
        name: dragon
logging:
    level:
        com.gatto.dragon.aop: DEBUG
        com.gatto.dragon.api: DEBUG
        com.gatto.dragon.logic: DEBUG
        com.gatto.dragon.strategy: DEBUG

